* File: inv.pex.netlist.INV.pxi
* Created: Mon Apr 15 16:30:49 2019
* 
x_PM_INV_VDD N_VDD_M1_b N_VDD_M1_s VDD PM_INV_VDD
x_PM_INV_GROUND N_GROUND_M0_s N_GROUND_M0_b GROUND PM_INV_GROUND
x_PM_INV_OUT N_OUT_M0_d N_OUT_M1_d OUT PM_INV_OUT
x_PM_INV_IN N_IN_M0_g N_IN_M1_g IN PM_INV_IN
